# Generated by Django 3.2.17 on 2023-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230213_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/feature-img1.jpg', upload_to='blog/'),
        ),
    ]
